//information of each city

export default {
    Seoul: [{
        name: 'Namsan Tower',
        img: '', //require('@/assets/images/namsan.jpg'),
        desc: 'The N Seoul Tower (Korean: N서울타워), officially the N Seoul Tower and commonly known as Namsan Tower or Seoul Tower, is a communication and observation tower located on Namsan Mountain in central Seoul, South Korea. The 236-meter (774 ft)-tall tower marks the second highest point in Seoul.',  
        address: '105 Namsangongwon-gil, Yongsan 2(i)ga-dong, Yongsan-gu, Seoul',
        reveal: false,
    },
    {
        name: 'Yeouido Hangang Park',
        img: '', //require('@/assets/images/yeouido.jpg'),
        desc: 'Yeouido Park offers a forest, a lawn and an ecological pond in the heart of the city. Many citizens of Seoul come to this park to enjoy light exercise or walk. You can enjoy roller blading and a bicycle ride in the Culture Center, which is located in the middle of this park.',
        address: '330, Yeouidong-ro, Yeongdeungpo-gu, Seoul',
        reveal: false,
    },
    {
        name: 'Gyeongbokgung Palace',
        img: '', //require('@/assets/images/gyeongbokgung.png'),
        desc: 'It was the largest palace built during the Joseon Dynasty. When visiting Gyeongbokgung Palace, the National Palace Museum and the National Folk Museum are also good to visit together. Night opening, which enters after 7 p.m. is popular.',
        address: 'Gyeongbokgung Palace, 161 Sajik-ro, Jongno-gu, Seoul',
        reveal: false,
    },
    {
        name: 'Cheonggyecheon',
        img: '', //require('@/assets/images/cheonggyecheon.jpeg'),
        desc: 'At the starting point of Cheonggyecheon Stream, there is a candle fountain with three-color lights and a two-stage waterfall that falls 4m below. If you follow Cheonggyecheon Stream, you will find Dongdaemun DDP, a landmark in Seoul where rest, culture, and history coexist.',  
        address: 'Changshin-dong, Jongno-gu, Seoul',
        reveal: false,
    },
    {
        name: 'Insadong',
        img: '', //require('@/assets/images/insadong.png'),
        desc: 'Insadong has long been loved by artists and writers. They gathered to form a commercial district and created Insadong, which is proud to be a space for traditional culture. It is the town with the deepest knowledge of culture and arts, and there are many traditional souvenir shops.',
        address: '44 Ssamji-gil, Insadong-gil, Jongno-gu, Seoul',
        reveal: false,
    },
    {
        name: 'Bukchon Hanok Village',
        img: '', //require('@/assets/images/hanokvillage.jpeg'),
        desc: 'It is the only place in Seoul where traditional hanoks are gathered. Hanoks, historical and cultural resources, museums, and workshops are located throughout the winding maze-like alleys. The Bukchon Cultural Center is holding traditional cultural lectures such as calligraphy, tea ceremony, and pansori, as well as cultural events such as movie screenings and concerts.', 
        address: '37 Gyedong-gil, Jongno-gu, Seoul',
        reveal: false,
    },
    {
        name: 'Seoul Forest',
        img: '', //require('@/assets/images/seoulforest.jpeg'),
        desc: 'Seoul Forest consists of four distinctive spaces: Culture and Arts Park, Experience Learning Center, Ecological Forest, and Wetland Ecological Center, and borders the Hangang River. You can enjoy the wonderful scenery of Eungbongsan Mountain, located opposite Seoul Forest, like a mirror on a mirror pond.',  
        address: '273 Ttukseom-ro, Seongdong-gu, Seoul',
        reveal: false,
    },
    {
        name: 'Naksan Park',
        img: '', //require('@/assets/images/naksan.png'),
        desc: 'Naksan Park is a night view spot where you can walk along the fortress of Hanyang City Wall, take a walk, and enjoy the night view of Seoul. The road to the mountain is divided into Hyehwamun, Dongdaemun, and Daehak-ro. We recommend going up through Ewha Village, where murals are located.',
        address: '41 Naksan-gil, Jongno-gu, Seoul',
        reveal: false,
    }],

    Busan: [{
        name: 'Gwangalli',
        img: '', //require('@/assets/images/gwangalli.png'),
        desc: '-.',
        address: '219, Gwangan Beach-ro, Suyeong-gu, Busan',
        reveal: false,
    },
    {
        name: 'Haeundae',
        img: '', //require('@/assets/images/haeundae.png'),
        desc: '-.',
        address: 'U-dong, Haeundae-gu, Busan',
        reveal: false,
    },
    {
        name: 'Huinyeoul Culture Village',
        img: 'Images/haeundae.png',
        desc: '-.',
        address: '605-3 Yeongseon-dong 4-ga, Yeongdo-gu, Busan',
        reveal: false,
    },
    {
        name: 'Gamcheon Culture Village',
        img: 'Images/haeundae.png',
        desc: '-.', 
        address: '203 Gamcheon Culture Village Information Center, Gamnae 2-ro, Saha-gu, Busan',
        reveal: false,
    },
    {
        name: 'Haedong Yonggungsa Temple',
        img: 'Images/haeundae.png',
        desc: '-.',
        address: '86 Yonggung-gil, Gijang-eup, Gijang-gun, Busan',
        reveal: false,
    },
    {
        name: 'Taejongdae',
        img: 'Images/haeundae.png',
        desc: '-.',
        address: '24, Jeonmang-ro, Yeongdo-gu, Busan',
        reveal: false,
    },
    {
        name: 'Yeongdo Bongsan Village',
        img: 'Images/haeundae.png',
        desc: '-.',
        address: '788, Hana-gil, Yeongdo-gu, Busan',
        reveal: false,
    },
    {
        name: 'Choryang Ibagu-gil',
        img: 'Images/haeundae.png',
        desc: '-.',
        address: '865-48, Choryang-dong, Dong-gu, Busan',
        reveal: false,
    }]
}